apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
  labels:
    app: aggregator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
        - name: aggregator-service
          image: gcr.io/healthsync-443607/aggregator-service:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/aggregator-service/actuator/health
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/v1/aggregator-service/actuator/health
            initialDelaySeconds: 40
            periodSeconds: 10
#          resources:
#            requests:
#              cpu: "300m"
#              memory: "400Mi"
#            limits:
#              cpu: "500m"
#              memory: "512Mi"